marketplace/app_basket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import add_to_cart, get_cart, remove_from_cart, change_cart

app_name = "app_basket"

urlpatterns = [
    path('', get_cart, name='cart'),
    path('add/', add_to_cart, name='add_to_cart'),
    path('remove/', remove_from_cart, name='remove_from_cart'),
    path('change/', change_cart, name='change_cart'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/app_merch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (AllDiscountView, CatalogView, DiscountDetailView,
                    DiscountListView, IndexView, OrderDeliveryView,
                    OrderPaymentView, OrderPurchaseView, OrderUserDataView,
                    ProductDetailView, PaymentView, ComparisonView,
                    import_products, add_to_comparison_list, remove_from_comparison_list, clear_comparison_list)

app_name = "pages"

urlpatterns = [
    path('', IndexView.as_view(), name='index-page'),
    path('products/', CatalogView.as_view(), name='catalog-view'),
    path('products/all_product_discounts/', AllDiscountView.as_view(), name='all-discounts'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('order/userdata/', OrderUserDataView.as_view(), name='order-step-1'),
    path('order/delivery/', OrderDeliveryView.as_view(), name='order-step-2'),
    path('order/payment/', OrderPaymentView.as_view(), name='order-step-3'),
    path('order/purchase/', OrderPurchaseView.as_view(), name='order-step-4'),
    path('order/send-payment/', PaymentView.as_view(), name='payment-view'),
    path("discounts/", DiscountListView.as_view(), name="discount_list"),
    path("discounts/<int:pk>/", DiscountDetailView.as_view(), name="discount_detail"),
    path("comparison/", ComparisonView.as_view(), name="comparison"),
    path("import-products/", import_products, name='import_page'),
    path("add_to_comparison_list/", add_to_comparison_list, name='add_to_comparison_list'),
    path("remove_from_comparison_list/", remove_from_comparison_list, name='remove_from_comparison_list'),
    path("clear_comparison_list/", clear_comparison_list, name='clear_comparison_list'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/clearcache/", include("clearcache.urls")),
    path("admin/", admin.site.urls),
    path("", include("app_merch.urls")),
    path("users/", include("app_users.urls")),
    path("cart/", include("app_basket.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/templates/base.html
{% load static %}
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->
<head>
    <title>{% block title %}Megano{% endblock %}</title>
    {% block meta_page_description %}{% endblock %}
    {% include 'includes/head.html' %}
</head>
<body class="Site">
    <header class="Header">
        {% include 'includes/header.html' %}
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="Footer">
        {% include 'includes/footer.html' %}
    </footer>
    {% block page_scripts %}
    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js'%}"></script>
    <script src="{% static 'assets/plg/form/jquery.form.js'%}"></script>
    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js'%}"></script>
    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js'%}"></script>
    <script src="{% static 'assets/plg/Slider/slick.min.js'%}"></script>
    <script src="{% static 'assets/js/scripts.js'%}"></script>
    {% endblock %}
</body>
</html>

marketplace/templates/base_mini.html
{% load static %}
<!--END-->
<!--END-->
<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie7" lang="ru">
<![endif]-->
<!--[if IE 8]>
<html class="ie8" lang="ru">
<![endif]-->
<!--[if IE 9]>
<html class="ie9" lang="ru">
<![endif]-->
<!--[if IE 10]>
<html class="ie10" lang="ru">
<![endif]-->
<!--[if IE 11]>
<html class="ie11" lang="ru">
<![endif]-->
<!--[if gt IE 11]><!-->
<html lang="ru">
<!--<![endif]-->
<head>
    <title>{% block title %}Megano{% endblock %}</title>
    {% block meta_page_description %}{% endblock %}
    {% include 'includes/head.html' %}
</head>
<body class="Site">
    <header class="Header">
        {% include 'includes/header_mini.html' %}
    </header>
    <main>
        {% block main %}
        {% endblock %}
    </main>
    <footer class="Footer">
        {% include 'includes/footer.html' %}
    </footer>
    {% block page_scripts %}
    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js'%}"></script>
    <script src="{% static 'assets/plg/form/jquery.form.js'%}"></script>
    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js'%}"></script>
    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js'%}"></script>
    <script src="{% static 'assets/plg/Slider/slick.min.js'%}"></script>
    <script src="{% static 'assets/js/scripts.js'%}"></script>
    {% endblock %}
</body>
</html>

marketplace/templates/cart.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
<div class="Middle Middle_top" xmlns="http://www.w3.org/1999/html">
        <div class="Section">
            <div class="wrap">
                <form id="change2" action="{% url 'app_basket:change_cart' %}" method="post">
                    {% csrf_token %}
                    {% for cartitem in cart_user %}
                    <div class="Cart-product">
                        <div class="Cart-block Cart-block_row">
                            <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="#"><img class="Cart-img" src="/{% firstof cartitem.offer.product.icon.file 'static/assets/img/content/home/no-pic.png' %}" alt="bigGoods2.jpg" /></a>
                            </div>
                            <div class="Cart-block Cart-block_info"><a class="Cart-title" href="{% url 'pages:product-detail' cartitem.offer.product.pk %}">{{cartitem.offer.product.title}}</a>
                                <div class="Cart-desc">{{cartitem.offer.product.description}}</div>
                            </div>

                        </div>
                            <div class="Cart-block Cart-block_row">
                                <div class="Cart-block Cart-block_seller">
                                    <div class="Cart-desc">{% trans "Продавец" %}: {{cartitem.offer.seller}}</div>
                                <!-- - var options = setOptions(items, ['value', 'selected', 'disabled']);-->

                                </div>
                                <div class="Cart-block Cart-block_price">
                                <div class="Cart-desc">{% trans "Цена за ед." %}</div>
                                <div class="Cart-price">{{cartitem.price|floatformat:2}}&nbsp;₽</div>
                            </div>
                            <div class="Cart-block Cart-block_amount">
                                <div class="Cart-amount">

                                            <style>
                                                .raz {
                                                    all: unset;
                                                    -moz-appearance: textfield;
                                                    width: 1.2em;
                                                    text-align: center;
                                                    font-size: 1.5em;
                                                    }
                                                    .raz::-webkit-inner-spin-button {
                                                    display: none;
                                                    }
                                            </style>

                                        <form action="{% url 'app_basket:change_cart' %}" method="post">
                                            {% csrf_token %}
                                        <button style="font-size:2em; padding: 1px 8.5px;" type="button" onclick="this.nextElementSibling.stepDown()">-</button>
                                        <input name="amount" type="number" min="1" max="{{cartitem.offer.quantity}}" step="1" value="{{cartitem.quantity}}" class="raz"/>
                                        <button style="font-size:1.8em; padding: 1px 5.5px; "type="button" onclick="this.previousElementSibling.stepUp()">+</button>
                                        <input style="background-color: #ebebeb; color: black; border: 1px solid red" type="submit" value='{% trans "Изменить" %}'>
                                        <input type="hidden" name="cartitem_id" value="{{ cartitem.id }}">
                                        </form>

                                </div>
                            </div>
                            <div class="Cart-block Cart-block_price">
                                <div class="Cart-desc">{% trans "Сумма за" %} {{cartitem.quantity}} {% trans "шт" %}</div>
                                <div class="Cart-price">{{cartitem.total_price|floatformat:2}}&nbsp;₽</div>
                            </div>
                            <div class="Cart-block Cart-block_delete"><a class="Cart-delete" href="{% url 'app_basket:remove_from_cart' %}?cartitem_id={{cartitem.id}}"><img src="{% static '/assets/img/icons/card/delete.svg'%}" alt="delete.svg" /></a>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    {% if cart_user %}
                    <div class="Cart-total">
                        <div class="Cart-block Cart-block_row">
                            <strong class="Cart-title">{% trans "Итого" %}:</strong>
                            <span class="Cart-price">{{price}} ₽</span>
                            <div class="Cart-price" style="width:5px"></div>
                            {% if discount_cart == True %}
                            <strong class="Cart-title">{% trans "Скидка на корзину" %}:</strong>
                            <span class="Cart-price">{{discount|floatformat:2}} $</span>
                            {% elif discount_cart == False %}
                            <strong class="Cart-title">{% trans "Скидка на набор" %} "{{discount.0}}":</strong>
                            <span class="Cart-price">{{discount.1|floatformat:2}} $</span>
                            {% elif not discount_cart %}
                            <strong class="Cart-title">{% trans "Скидка" %}: </strong>
                            <span class="Cart-price">{{discount|floatformat:2}} ₽</span>
                            {% endif %}

                            <div class="Cart-price" style="width:10px"></div>
                            <strong class="Cart-title">{% trans "Сумма со скидкой" %}:
                            <span class="Cart-price" style="color:red">{{total_price|floatformat:2}} ₽</span>
                            </strong>


                        <div class="Cart-block"><a class="btn btn_success btn_lg" href="{% url 'pages:order-step-1' %}">{% trans "Оформить заказ " %}</a>
                        </div>
                    </div>
                    {% else %}
                        <div align="center">
                        <strong class="Cart-title">{% trans "Ваша корзина пуста" %}. <a href="{% url 'pages:catalog-view' %}">{% trans "Продолжить покупки" %}</a>.
                        </strong>
                        <img src="{% static 'assets/img/content/home/empty_cart.jpg' %}" alt="empty_cart" style="max-width: 500px; width: 100%"/>
                        </div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
{% endblock %}

marketplace/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
        <div class="Header-slider">
            <div class="Slider Slider_main">
              <div class="Slider-box">
                  {% for banner in banners %}
                <div class="Slider-item">
                  <div class="Slider-content">
                    <div class="row">
                      <div class="row-block">
                        <strong class="Slider-title">{{ banner.title }}
                            {% if banner.primary_text %}
                            <span class="text_primary">{{ banner.primary_text }}</span>
                            {% endif %}
                        </strong>
                        <div class="Slider-text">{{ banner.description|truncatechars:100 }}
                        </div>
                        <div class="Slider-footer"><a class="btn btn_primary" href="{{ banner.link }}">{% trans "Начать" %}</a>
                        </div>
                      </div>
                      <div class="row-block">
                        <div class="Slider-img"><img src="/{% firstof banner.file.file 'static/assets/img/content/home/slider.png' %}" width="735" height="454" alt="bnr_img"/>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                  {% endfor %}
              </div>
              <div class="Slider-navigateWrap">
                <div class="Slider-navigate">
                </div>
              </div>
            </div>
        </div>
    <div class="Middle">
        <div class="Section">
            <div class="wrap">
                <div class="BannersHome">
                    {% for category in categories %}
                    <a class="BannersHomeBlock" href="{% url "pages:catalog-view" %}?cat={{ category.slug }}">
                        <div class="BannersHomeBlock-row">
                            <div class="BannersHomeBlock-block">
                                <strong class="BannersHomeBlock-title">{{ category.title }}
                                </strong>
                                <div class="BannersHomeBlock-content"> от <span class="BannersHomeBlock-price"> {{ category.min_price|floatformat:2 }} руб.</span>
                                </div>
                            </div>
                            <div class="BannersHomeBlock-block">
                                <div class="BannersHomeBlock-img"><img src="/{% firstof category.products.first.icon.file 'static/assets/img/content/home/videoca.png' %}" alt="videoca.png" />
                                </div>
                            </div>
                        </div>
                    </a>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
            <div class="Section Section_column Section_columnLeft Section_columnDesktop">
            <div class="wrap">
                {% if limited_edition %}
                <div class="Section-column">
                    <div class="Section-columnSection Section-columnSection_mark">
                      <header class="Section-columnHeader">
                        <strong class="Section-columnTitle">ПРЕДЛОЖЕНИЕ ДНЯ
                        </strong>
                      </header>
                      <div class="Card"><a class="Card-picture" href="{% url "pages:product-detail" limited_edition.product.pk %}"><img src=/{% firstof limited_edition.product.icon.file "assets/img/content/home/card.jpg"%} alt="card.jpg"/></a>
                        <div class="Card-content">
                          <strong class="Card-title"><a href="{% url "pages:product-detail" limited_edition.product.pk %}">{{ limited_edition.product.title }}</a>
                          </strong>
                          <div class="Card-description">
                            <div class="Card-cost"><span class="Card-priceOld">{{ limited_edition.price }} руб.</span><span class="Card-price" style="color:red">{{ limited_edition.sale|floatformat:2 }} руб.</span>
                            </div>
                            <div class="Card-category">{{ limited_edition.product.category.title }}
                            </div>
                          </div>
                          <div class="CountDown" data-date="{{ limited_edition_date }}">
                            <div class="CountDown-block">
                              <div class="CountDown-wrap">
                                <div class="CountDown-days">
                                </div><span class="CountDown-label">days</span>
                              </div>
                            </div>
                            <div class="CountDown-block">
                              <div class="CountDown-wrap">
                                <div class="CountDown-hours">
                                </div><span class="CountDown-label">hours</span>
                              </div>
                            </div>
                            <div class="CountDown-block">
                              <div class="CountDown-wrap">
                                <div class="CountDown-minutes">
                                </div><span class="CountDown-label">mins</span>
                              </div>
                            </div>
                            <div class="CountDown-block">
                              <div class="CountDown-wrap">
                                <div class="CountDown-secs">
                                </div><span class="CountDown-label">secs</span>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div> {% endif %}
                </div>
                <div class="Section-content">
                    <header class="Section-header">
                        <h2 class="Section-title">Популярные товары
                        </h2>
                    </header>
                    <div class="Cards">
                        {% for offer in top_products %}
                        <div class="Card"><a class="Card-picture" href="{% url 'pages:product-detail' offer.product.pk %}"><img src=/{% firstof offer.product.icon.file "assets/img/content/home/card.jpg"%} alt="card.jpg" /></a>
                            <div class="Card-content">
                                <strong class="Card-title"><a href="{% url 'pages:product-detail' offer.product.pk %}">{{ offer.product.title }}</a>
                                </strong>
                                <div class="Card-description">
                                    <div class="Card-cost"><span class="Card-price">{{ offer.price }} руб.</span>
                                    </div>
                                    <div class="Card-category">{{ offer.product.category.title }}
                                    </div>
                                    <div class="Card-hover">
                                        <a class="Card-btn" href="{% url 'app_basket:add_to_cart'%}?offer_id={{ offer.pk }}">
                                            <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg" />
                                        </a>
                                        <a class="Card-btn" href="{% url 'pages:add_to_comparison_list'%}?product={{ offer.product.pk }}">
                                            <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg" />
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="Section Section_column Section_columnRight">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Slider Slider_carousel">
                        <header class="Section-header Section-header_close">
                            <h2 class="Section-title">Ограниченный тираж
                            </h2>
                            <div class="Section-control">
                                <div class="Slider-navigate">
                                </div>
                            </div>
                        </header>
                        <div class="Slider-box Cards">
                            {% for offer in limited_edition_list %}
                            <div class="Slider-item">
                                <div class="Slider-content">
                                    <div class="Card"><a class="Card-picture" href="{% url "pages:product-detail" offer.product.pk %}"><img src=/{% firstof offer.product.icon.file "assets/img/content/home/card.jpg"%} alt="card.jpg" /></a>
                                        <div class="Card-content">
                                            <strong class="Card-title"><a href="{% url "pages:product-detail" offer.product.pk %}">{{ offer.product.title }}</a>
                                            </strong>
                                            <div class="Card-description">
                                                <div class="Card-cost"><span class="Card-price">{{ offer.price }} руб.</span>
                                                </div>
                                                <div class="Card-category">{{ offer.product.category.title }}
                                                </div>
                                                <div class="Card-hover">
                                                    <a class="Card-btn" href="{% url 'app_basket:add_to_cart'%}?offer_id={{ offer.pk }}">
                                                        <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg" />
                                                    </a>
                                                    <a class="Card-btn" href="{% url 'pages:add_to_comparison_list'%}?product={{ offer.product.pk }}">
                                                        <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg" />
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

marketplace/templates/seller.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}

    <div class="Middle Middle_top">
            <div class="Middle-top">
                <div class="wrap">
                    <div class="Middle-header">
                        <h1 class="Middle-title">{{ seller.title }}
                        </h1>
                    </div>
                </div>
            </div>
            <div class="Section Section_column Section_columnLeft">
                <div class="wrap">
                    <div class="Section-column">
                        <div class="Section-columnSection">
                            <div class="Section-columnContent">
                                <div class="Profile-avatar">
                                    <div class="Profile-img"><img src="/{% firstof seller.profile.avatar.file 'assets/img/icons/profile.png' %}" alt="profile.png">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="Section-content">
                        <div class="Profile">
                            <div class="row">
                                <div class="row-block">
                                    <div class="form-group">
                                    </div>
                                    <div class="">
                                        <label class="label" for="name">{% trans "Описание" %}
                                        </label>
                                        <div>{{ seller.description }}</div>
                                    </div>
                                </div>
                                <div class="row-block">
                                    <div class="">
                                        <label class="label" for="phone">{% trans "Телефон" %}
                                        </label>
                                        <div>{{ seller.profile.phone_number }}</div>
                                    </div>
                                    <div class="">
                                        <label class="label" for="mail">Email
                                        </label>
                                        <div>{{ seller.profile.user.email }}</div>
                                    </div>
                                    <div class="">
                                        <label class="label" for="address">{% trans "Адрес" %}
                                        </label>
                                        <div>{{ seller.profile.address }}</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="Section Section_column Section_columnRight">
            <div class="wrap">
                <div class="Section-content">
                    <div class="Slider Slider_carousel">
                        <header class="Section-header Section-header_close">
                            <h2 class="Section-title">{% trans "Топ 10 товаров" %}
                            </h2>
                            <div class="Section-control">
                                <div class="Slider-navigate">
                                </div>
                            </div>
                        </header>
                        <div class="Slider-box Cards">
                            {% for offer in offers %}
                                <div class="Slider-item">
                                    <div class="Slider-content">
                                        <div class="Card"><a class="Card-picture" href="{% url 'pages:product-detail' offer.product.pk %}"><img src="/{{ offer.product.icon.file }}" alt="card.jpg" /></a>
                                            <div class="Card-content">
                                                <strong class="Card-title"><a href="{% url 'pages:product-detail' offer.product.pk %}">{{ offer.product.title }}</a>
                                                </strong>
                                                <div class="Card-description">
                                                    <div class="Card-cost"><span class="Card-price">{{ offer.price }} руб.</span>
                                                    </div>
                                                    <div class="Card-category">{{ offer.product.category.title }}
                                                    </div>
                                                    <div class="Card-hover">
                                                        <a class="Card-btn" href="{% url 'app_basket:add_to_cart'%}?offer_id={{ offer.pk }}">
                                                            <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg" />
                                                        </a>
                                                        <a class="Card-btn" href="{% url 'pages:add_to_comparison_list'%}?product={{ offer.product.pk }}">
                                                            <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg" />
                                                        </a>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}