marketplace/app_merch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (AllDiscountView, CatalogView, DiscountDetailView,
                    DiscountListView, IndexView, OrderDeliveryView,
                    OrderPaymentView, OrderPurchaseView, OrderUserDataView,
                    ProductDetailView, PaymentView, ComparisonView,
                    import_products, add_to_comparison_list, remove_from_comparison_list, clear_comparison_list)

app_name = "pages"

urlpatterns = [
    path('', IndexView.as_view(), name='index-page'),
    path('products/', CatalogView.as_view(), name='catalog-view'),
    path('products/all_product_discounts/', AllDiscountView.as_view(), name='all-discounts'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('order/userdata/', OrderUserDataView.as_view(), name='order-step-1'),
    path('order/delivery/', OrderDeliveryView.as_view(), name='order-step-2'),
    path('order/payment/', OrderPaymentView.as_view(), name='order-step-3'),
    path('order/purchase/', OrderPurchaseView.as_view(), name='order-step-4'),
    path('order/send-payment/', PaymentView.as_view(), name='payment-view'),
    path("discounts/", DiscountListView.as_view(), name="discount_list"),
    path("discounts/<int:pk>/", DiscountDetailView.as_view(), name="discount_detail"),
    path("comparison/", ComparisonView.as_view(), name="comparison"),
    path("import-products/", import_products, name='import_page'),
    path("add_to_comparison_list/", add_to_comparison_list, name='add_to_comparison_list'),
    path("remove_from_comparison_list/", remove_from_comparison_list, name='remove_from_comparison_list'),
    path("clear_comparison_list/", clear_comparison_list, name='clear_comparison_list'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/app_users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (AccountView, CustomLoginView, CustomLogoutView, CustomPasswordResetConfirmView,
                    CustomPasswordResetDoneView, CustomPasswordResetView,
                    CustomRegisterView, OrderDetailView, OrdersHistoryView,
                    ProfileEditView, SellerView, ViewsHistoryView, CustomPasswordResetCompleteView)

app_name = "app_users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset/complete/", CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("register/", CustomRegisterView.as_view(), name="register"),
    path("seller/<int:pk>/", SellerView.as_view(), name="seller_detail"),
    path("profile/<slug:username>/", AccountView.as_view(), name="account"),
    path(
        "profile/<slug:username>/edit/", ProfileEditView.as_view(), name="profile_edit"
    ),
    path("my/orders/", OrdersHistoryView.as_view(), name="orders_history"),
    path("my/orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
    path(
        "profile/<slug:username>/views/",
        ViewsHistoryView.as_view(),
        name="views_history",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/clearcache/", include("clearcache.urls")),
    path("admin/", admin.site.urls),
    path("", include("app_merch.urls")),
    path("users/", include("app_users.urls")),
    path("cart/", include("app_basket.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/templates/includes/footer.html
{% load i18n %}
{% load static %}

        <div class="wrap">
            <div class="row Footer-main">
                <div class="row-block"><a class="logo Footer-logo" href="{% url 'pages:index-page' %}"><img class="logo-image" src="{% static 'assets/img/logo_footer.png'%}" alt="logo_footer.png" /></a>
                </div>
                <div class="row-block">
                    <strong class="Footer-title">{% trans "Навигация" %}
                    </strong>
                    <ul class="menu menu_vt Footer-menu">
                        <li class="menu-item"><a class="menu-link" href="{% url 'pages:index-page' %}">{% trans "Главная" %}</a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="{% url 'pages:catalog-view' %}">{% trans "Каталог" %}</a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="{% url 'pages:comparison' %}">{% trans "Сравнение" %}</a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="{% url 'app_users:account' request.user.is_authenticated %}">{% trans "Профиль" %}</a>
                        </li>

                    </ul>
                </div>
                <div class="row-block">
                    <strong class="Footer-title">{% trans "Контакты" %}
                    </strong>
                    <p>Phone: 8.800.200.600<br>Email: xxx@meg.com<br>
                    </p>
                    <ul class="menu menu_img menu_smallImg Footer-menuSoc">
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/fb.svg'%}" alt="fb.svg" /></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/tw.svg'%}" /></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/in.svg'%}" alt="in.svg" /></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/pt.svg'%}" alt="pt.svg" /></a>
                        </li>
                        <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialFooter/mail.svg'%}" alt="mail.svg" /></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    <script src="{% static 'assets/plg/jQuery/jquery-3.5.0.slim.min.js'%}"></script>
    <script src="{% static 'assets/plg/form/jquery.form.js'%}"></script>
    <script src="{% static 'assets/plg/form/jquery.maskedinput.min.js'%}"></script>
    <script src="{% static 'assets/plg/range/ion.rangeSlider.min.js'%}"></script>
    <script src="{% static 'assets/plg/Slider/slick.min.js'%}"></script>

marketplace/templates/includes/head.html
{% load static %}

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <link href="{% static 'assets/img/favicon.ico' %}" rel="shortcut icon">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Regular.woff'%}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Italic.woff'%}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold.woff'%}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Bold_Italic.woff'%}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light.woff'%}" as="font">
    <link rel="preload" href="{% static 'assets/fonts/Roboto/Roboto-Light_Italic.woff'%}" as="font">
    <link rel="stylesheet" href="{% static 'assets/css/fonts.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/basic.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/extra.css'%}">
    <link rel="stylesheet" href="{% static 'assets/css/custom.css' %}">
    <script src="{% static 'assets/plg/CountDown/countdown.js'%}"></script>
    <!--[if lt IE 9]>
  <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

marketplace/templates/includes/header.html
{% load i18n %}
{% load static %}
{% load mptt_tags %}
{% load category_tags %}
        <div class="ControlPanel">
            <div class="wrap">
                <div class="row ControlPanel-row">
                    <div class="row-block">
                        <div class="row ControlPanel-rowSplit">
                            <div class="row-block hide_700">
                                <ul class="menu menu_img menu_smallImg ControlPanel-menu">
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/tw.svg' %}" alt="tw.svg" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/in.svg' %}" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/pt.svg' %}" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/mail.svg' %}" /></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <nav class="row-block">
                        <div class="row ControlPanel-rowSplit">
                            <div class="row-block">
                                {% if request.user.is_anonymous %}
                                    <a class="ControlPanel-title" href="{% url 'app_users:login' %}">{% trans "Вход" %}</a>
                                    <a class="ControlPanel-title" href="{% url 'app_users:register' %}">{% trans "Регистрация" %}</a>
                                {% endif %}
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
            <!--+div.menuModal#navigate
      //    +menu([
      //        ['Главная','index.html'],
      //        ['Портфолио','index.html'],
      //        ['Мои проекты','index.html'],
      //        ['Контакты','index.html']
      //    ], page === 'article'? 'Портфолио': 'Главная')._main

      block
      -->
        </div>
        <div class="wrap">
            <div class="row Header-rowMain">
                <div class="row-block Header-logo"><a class="logo" href="{% url 'pages:index-page' %}"><img class="logo-image" src="{% static 'assets/img/logo.png' %}" alt="logo.png" /></a>
                </div>
                <nav class="row-block row-block_right Header-menu">
                    <div class="menuModal" id="navigate">
                        <ul class="menu menu_main">
                            <li class="menu-item"><a class="menu-link" href="{% url 'pages:index-page' %}">{% trans "Главная" %}</a>
                            </li>
                            <li class="menu-item"><span class="menu-label menu-label_success">{% trans "Скидки" %}</span><a class="menu-link" href="{% url 'pages:catalog-view' %}">{% trans "Каталог" %}</a>
                            </li>
                            <li class="menu-item"><a class="menu-link" href="{% url 'pages:all-discounts' %}">{% trans "Предложения" %}</a>
                            </li>
                            <li class="menu-item"><a class="menu-link" href="{% url 'pages:discount_list' %}">{% trans "Скидки" %}</a>
                            </li>
                            <li class="menu-item"><a class="menu-link" href="{% url 'pages:comparison' %}">{% trans "Сравнение" %}</a>
                            </li>
                            {% if request.user.is_staff %}
                                <li class="menu-item"><a class="menu-link" href="{% url 'pages:import_page' %}">{% trans "Импорты" %}</a>
                                </li>
                            {% endif %}
                            <!--<li>
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-sm-2">
                                            {% block sidebar %}
                                                <ul class="sidebar-nav">
                                                   <li>
                                                       <form action="{% url 'set_language' %}" method="post">
                                                            {% csrf_token %}
                                                            <select name="language">
                                                                {% get_current_language as LANGUAGE_CODE %}
                                                                {% get_available_languages as LANGUAGES %}
                                                                {% get_language_info_list for LANGUAGES as languages %}
                                                                {% for language in languages %}
                                                                    <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected {% endif %}>
                                                                        {{ language.name_local }} ({{ language.code }})
                                                                    </option>
                                                                {% endfor %}
                                                            </select>
                                                            <input type="submit" value="{% trans 'Go' %}">
                                                       </form>
                                                   </li>

                                                </ul>
                                            {% endblock %}
                                        </div>
                                    </div>
                                </div>
                            </li>-->
                        </ul>
                    </div>
                </nav>
                <div class="row-block">

                    <div class="CartBlock">
                        {% if not request.user.is_anonymous %}
                        <div class="dropdown">
                            <button class="dropbtn"><img class="CartBlock-img" src="{% static 'assets/img/icons/loon-icon.svg'%}" alt="loon-icon.svg" /></button>
                            <div class="dropdown-content">
                                <a class="dropdown-content-a" href="{% url "app_users:account" request.user.username %}">{% trans "Личный кабинет" %}</a>
                                <a class="dropdown-content-a" href="/admin">{% trans "Административный раздел" %}</a>
                                <a class="dropdown-content-a" href="/users/logout">{% trans "Выход" %}</a>
                            </div>
                        </div>
                        {% endif %}
                        <a class="CartBlock-block" href="/cart"><img class="CartBlock-img" src="{% static 'assets/img/icons/cart.svg'%}" alt="cart.svg" /><span class="CartBlock-amount">{{cart.get_cart_item_quantity}}</span></a>
                        <div class="CartBlock-block"><span class="CartBlock-price">{{ price_after_discount|floatformat:2 }}₽</span></div>
                    </div>
                </div>
                <div class="row-block Header-trigger"><a class="menuTrigger" href="#navigate">
                        <div class="menuTrigger-content">{% trans "Показать навигацию" %}
                        </div><span></span><span></span><span></span>
                    </a>
                </div>
            </div>
        </div>
        <div class="Header-searchWrap">
            <div class="wrap">
                <div class="Header-categories">
                    <div class="CategoriesButton">
                        <div class="CategoriesButton-title">
                            <div class="CategoriesButton-icon"><img src="{% static 'assets/img/icons/allDep.svg'%}" alt="allDep.svg" />
                            </div><span class="CategoriesButton-text">{% trans "Все категории" %}</span>
                            <div class="CategoriesButton-arrow">
                            </div>
                        </div>
                        <div class="CategoriesButton-content">

                      {% get_categories as categories %}
                      {% recursetree categories %}
                            <div class="CategoriesButton-link"><a href="{% url 'pages:catalog-view' %}?cat={{ node.slug }}">
                                    <div class="CategoriesButton-icon"><img src="/{{ node.icon.file }}" alt="icon" />
                                    </div><span class="CategoriesButton-text">{{ node.title }}</span>
                                </a>
                                {% if not node.is_leaf_node %}
                                <a class="CategoriesButton-arrow" href="#"></a>
                                <div class="CategoriesButton-submenu">
                                    {{ children }}
                                </div>
                                {% endif %}
                            </div>

                      {% endrecursetree %}
                        </div>
                    </div>
                </div>
                <div class="Header-searchLink"><img src="{% static 'assets/img/icons/search.svg'%}" alt="search.svg" />
                </div>
                <div class="Header-search">
                    <div class="search">
                        <form class="form form_search" action="{% url 'pages:catalog-view' %}" method="get">
                            <input class="search-input" id="title" name="title" type="text" placeholder="NVIDIA GeForce RTX 3060" />
                            <button class="search-button" type="submit" name="search" id="search"><img src="{% static 'assets/img/icons/search.svg'%}" />{% trans "Поиск" %}
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>

marketplace/templates/includes/header_mini.html
{% load static %}

        <div class="ControlPanel">
            <div class="wrap">
                <div class="row ControlPanel-row">
                    <div class="row-block">
                        <div class="row ControlPanel-rowSplit">
                            <div class="row-block hide_700">
                                <ul class="menu menu_img menu_smallImg ControlPanel-menu">
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/tw.svg'%}" alt="tw.svg" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/in.svg'%}" alt="in.svg" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/pt.svg'%}" alt="pt.svg" /></a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="#"><img src="{% static 'assets/img/icons/socialHeader/mail.svg'%}" alt="mail.svg" /></a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <nav class="row-block"></nav>
                </div>
            </div>
            <!--+div.menuModal#navigate
      //    +menu([
      //        ['Главная','index.html'],
      //        ['Портфолио','index.html'],
      //        ['Мои проекты','index.html'],
      //        ['Контакты','index.html']
      //    ], page === 'article'? 'Портфолио': 'Главная')._main

      block
      -->
        </div>
        <div class="wrap">
            <div class="row Header-rowMain">
                <div class="row-block Header-logo"><a class="logo" href="{% url 'pages:index-page' %}"><img class="logo-image" src="{% static 'assets/img/logo.png'%}" alt="logo.png" /></a>
                </div>
            </div>
        </div>