marketplace/app_basket/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import add_to_cart, get_cart, remove_from_cart, change_cart

app_name = "app_basket"

urlpatterns = [
    path('', get_cart, name='cart'),
    path('add/', add_to_cart, name='add_to_cart'),
    path('remove/', remove_from_cart, name='remove_from_cart'),
    path('change/', change_cart, name='change_cart'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/app_merch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (AllDiscountView, CatalogView, DiscountDetailView,
                    DiscountListView, IndexView, OrderDeliveryView,
                    OrderPaymentView, OrderPurchaseView, OrderUserDataView,
                    ProductDetailView, PaymentView, ComparisonView,
                    import_products, add_to_comparison_list, remove_from_comparison_list, clear_comparison_list)

app_name = "pages"

urlpatterns = [
    path('', IndexView.as_view(), name='index-page'),
    path('products/', CatalogView.as_view(), name='catalog-view'),
    path('products/all_product_discounts/', AllDiscountView.as_view(), name='all-discounts'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('order/userdata/', OrderUserDataView.as_view(), name='order-step-1'),
    path('order/delivery/', OrderDeliveryView.as_view(), name='order-step-2'),
    path('order/payment/', OrderPaymentView.as_view(), name='order-step-3'),
    path('order/purchase/', OrderPurchaseView.as_view(), name='order-step-4'),
    path('order/send-payment/', PaymentView.as_view(), name='payment-view'),
    path("discounts/", DiscountListView.as_view(), name="discount_list"),
    path("discounts/<int:pk>/", DiscountDetailView.as_view(), name="discount_detail"),
    path("comparison/", ComparisonView.as_view(), name="comparison"),
    path("import-products/", import_products, name='import_page'),
    path("add_to_comparison_list/", add_to_comparison_list, name='add_to_comparison_list'),
    path("remove_from_comparison_list/", remove_from_comparison_list, name='remove_from_comparison_list'),
    path("clear_comparison_list/", clear_comparison_list, name='clear_comparison_list'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/app_users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (AccountView, CustomLoginView, CustomLogoutView, CustomPasswordResetConfirmView,
                    CustomPasswordResetDoneView, CustomPasswordResetView,
                    CustomRegisterView, OrderDetailView, OrdersHistoryView,
                    ProfileEditView, SellerView, ViewsHistoryView, CustomPasswordResetCompleteView)

app_name = "app_users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset/complete/", CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("register/", CustomRegisterView.as_view(), name="register"),
    path("seller/<int:pk>/", SellerView.as_view(), name="seller_detail"),
    path("profile/<slug:username>/", AccountView.as_view(), name="account"),
    path(
        "profile/<slug:username>/edit/", ProfileEditView.as_view(), name="profile_edit"
    ),
    path("my/orders/", OrdersHistoryView.as_view(), name="orders_history"),
    path("my/orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
    path(
        "profile/<slug:username>/views/",
        ViewsHistoryView.as_view(),
        name="views_history",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/clearcache/", include("clearcache.urls")),
    path("admin/", admin.site.urls),
    path("", include("app_merch.urls")),
    path("users/", include("app_users.urls")),
    path("cart/", include("app_basket.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/app_users/models.py
from django.contrib.auth.models import User
from django.core.cache import cache
from django.db import models
from django.db.models import Sum, F

User._meta.get_field("email")._unique = False


class Profile(models.Model):
    """
    Модель профиля пользователя.
    """

    user = models.OneToOneField(
        User,
        on_delete=models.PROTECT,
        related_name="profile",
        db_index=True,
        verbose_name="пользователь",
    )
    full_name = models.CharField(max_length=150, verbose_name="полное имя")
    phone_number = models.CharField(
        max_length=50, verbose_name="номер телефона", unique=True
    )
    address = models.CharField(max_length=255, verbose_name="адрес")
    avatar = models.ForeignKey(
        "app_merch.Image",
        on_delete=models.SET_NULL,
        related_name="profile",
        blank=True,
        null=True,
        verbose_name="аватар",
    )

    class Meta:
        verbose_name = "Профиль"
        verbose_name_plural = "Профили"

    def __str__(self):
        return self.full_name


class Seller(models.Model):
    """
    Модель продавца.
    """

    profile = models.OneToOneField(
        Profile,
        on_delete=models.PROTECT,
        related_name="seller",
        db_index=True,
        verbose_name="профиль",
    )
    title = models.CharField(max_length=100, verbose_name="название")
    description = models.TextField(max_length=1000, verbose_name="описание")

    class Meta:
        verbose_name = "Продавец"
        verbose_name_plural = "Продавцы"

    def __str__(self):
        return self.title

    def save(
        self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        """
        Сброс кеша при изменении продавца.
        """
        if cache.get(f"Seller {self.pk} top products"):
            cache.delete(f"Seller {self.pk} top products")
        super().save()

    def delete(self, using=None, keep_parents=False):
        """
        Сброс кеша при удалении продавца.
        """
        if cache.get(f"Seller {self.pk} top products"):
            cache.delete(f"Seller {self.pk} top products")
        super().delete()


class Buyer(models.Model):
    """
    Модель покупателя.
    """

    profile = models.OneToOneField(
        Profile,
        null=True,
        on_delete=models.PROTECT,
        related_name="buyer",
        db_index=True,
        verbose_name="покупатель",
    )
    views = models.ManyToManyField(
        "app_merch.Product", verbose_name="история просмотров"
    )

    class Meta:
        verbose_name = "Покупатель"
        verbose_name_plural = "Покупатели"

    def __str__(self):
        return f"{self.profile}"


class ComparisonList(models.Model):
    """
    Модель для списка сравнения продуктов.
    """

    profile = models.OneToOneField(
        Buyer,
        null=True,
        on_delete=models.PROTECT,
        related_name="compare",
        db_index=True,
        verbose_name="владелец списка",
    )
    offer = models.ForeignKey(
        "app_merch.Offer",
        null=True,
        on_delete=models.PROTECT,
        related_name="offer",
        db_index=True,
        verbose_name="список для сравнения",
    )

    class Meta:
        verbose_name = "Список сравнения"
        verbose_name_plural = "Списки сравнения"

    def add_to_list(self):
        pass

    def remove_from_list(self):
        pass

    def return_list(self):
        pass

    def return_amount_in_list(self):
        pass

    def __str__(self):
        return f"Список сравнения {self.profile}"


class PaymentType(models.Model):
    """Модель типа оплаты."""

    title = models.CharField(max_length=100, verbose_name="вид оплаты")
    is_active = models.BooleanField(default=True, verbose_name="активен")

    class Meta:
        verbose_name = "вид оплаты"
        verbose_name_plural = "виды оплаты"

    def __str__(self):
        return self.title


class Payment(models.Model):
    buyer = models.ForeignKey(
        Buyer,
        on_delete=models.PROTECT,
        related_name="payments",
        verbose_name="покупатель",
    )
    payment_type = models.ForeignKey(
        PaymentType,
        on_delete=models.PROTECT,
        related_name="payment",
        verbose_name="тип оплаты",
    )
    credit_card = models.CharField(max_length=8, verbose_name="номер счета", null=True)

    class Meta:
        verbose_name = "Тип оплаты"
        verbose_name_plural = "Типы оплаты"

    def __str__(self):
        return self.payment_type.title


class DeliveryType(models.Model):
    type = models.CharField(max_length=100, verbose_name="тип")
    price = models.DecimalField(max_digits=6, decimal_places=2, verbose_name="цена")

    class Meta:
        verbose_name = "Тип доставки"
        verbose_name_plural = "Типы доставок"

    def __str__(self):
        return self.type


class Order(models.Model):
    PAYMENT_STATUS_CHOISES = {
        ("not_paid", "Не оплачен"),
        ("paid", "Оплачен"),
    }

    ORDER_STATUS_CHOISES = {
        ("awaiting_payment", "Ожидает оплаты"),
        ("is_delivering", "Доставляется"),
        ("delivered", "Доставлен"),
    }

    buyer = models.ForeignKey(
        Buyer,
        on_delete=models.PROTECT,
        related_name="orders",
        db_index=True,
        verbose_name="покупатель",
    )
    payment = models.ForeignKey(
        Payment,
        on_delete=models.PROTECT,
        related_name="orders",
        verbose_name="тип оплаты",
        null=True,
    )
    payment_status = models.CharField(
        max_length=20, choices=PAYMENT_STATUS_CHOISES, verbose_name="статус оплаты"
    )
    address = models.JSONField(verbose_name="адрес", null=True)
    delivery_type = models.ForeignKey(
        DeliveryType,
        on_delete=models.PROTECT,
        related_name="orders",
        verbose_name="тип доставки",
        null=True,
    )
    order_date = models.DateTimeField(auto_now_add=True, verbose_name="дата заказа")
    departure_date = models.DateTimeField(
        null=True, blank=True, verbose_name="дата отправки"
    )
    delivery_date = models.DateTimeField(
        null=True, blank=True, verbose_name="дата доставки"
    )
    order_status = models.CharField(
        max_length=20,
        choices=ORDER_STATUS_CHOISES,
        verbose_name="статус доставки",
        null=True,
    )

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return f"Заказ {self.id} от {self.order_date}"

    @staticmethod
    def total_price(order):
        return order.annotate(
            price=Sum(F("order_items__offer__price") * F("order_items__quantity"))
        )


class OrderItem(models.Model):
    offer = models.ForeignKey(
        "app_merch.Offer",
        on_delete=models.PROTECT,
        related_name="order_items",
        db_index=True,
        verbose_name="предложение",
    )
    order = models.ForeignKey(
        Order,
        on_delete=models.PROTECT,
        related_name="order_items",
        db_index=True,
        verbose_name="заказ",
    )
    quantity = models.PositiveIntegerField(verbose_name="количество")

    class Meta:
        verbose_name = "Товар в заказе"
        verbose_name_plural = "Товары в заказе"

marketplace/templates/users/account.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans "Навигация" %}
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url "app_users:account" user.username %}">{% trans "Личный кабинет" %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:profile_edit" user.username %}">{% trans "Профиль" %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:orders_history" %}">{% trans "История заказов" %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:views_history" user.username %}">{% trans "История просмотра" %}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Account">
                        <div class="Account-group">
                            <div class="Account-column">
                                <div class="Account-avatar">
                                    <img src="/{% firstof user.profile.avatar.file 'static/assets/img/icons/profile.png' %}" alt="profile.png" />
                                </div>
                            </div>
                            <div class="Account-column">
                                <div class="Account-name">{{ user.profile.full_name }}
                                </div><a class="Account-editLink" href="{% url "app_users:profile_edit" user.username %}">{% trans "Редактировать профиль" %}</a>
                            </div>
                        </div>
                        <header class="Section-header">
                        <strong class="Section-title">{% trans "Последний заказ" %}
                        </strong>
                        </header>
                        <div class="Account-group">
                            {% if last_order %}
                                <div class="Account-column Account-column_full">
                                    <div class="Order Order_anons">
                                        <div class="Order-personal">
                                            <div class="row">
                                                <div class="row-block"><a class="Order-title" href="{% url "app_users:order_detail" last_order.id %}">{% trans "Заказ" %}&#32;<span class="Order-numberOrder">№{{ last_order.pk }}</span>&#32;{% trans "от" %}&#32;<span class="Order-dateOrder">{{ last_order.order_date|date:"d.m.Y" }}</span></a>
                                                    <div class="Account-editLink"><a href="{% url "app_users:orders_history" %}">{% trans "История заказов" %}</a>
                                                    </div>
                                                </div>
                                                <div class="row-block">
                                                    <div class="Order-info Order-info_delivery">
                                                        <div class="Order-infoType">{% trans "Тип доставки" %}:
                                                        </div>
                                                        <div class="Order-infoContent">{{ last_order.delivery_type }}
                                                        </div>
                                                    </div>
                                                    <div class="Order-info Order-info_pay">
                                                        <div class="Order-infoType">{% trans "Оплата" %}:
                                                        </div>
                                                        <div class="Order-infoContent">{{ last_order.payment }}
                                                        </div>
                                                    </div>
                                                    <div class="Order-info">
                                                        <div class="Order-infoType">{% trans "Общая стоимость" %}:
                                                        </div>
                                                        <div class="Order-infoContent">{{ last_order_cost }} $
                                                        </div>
                                                    </div>
                                                    <div class="Order-info Order-info_status">
                                                        <div class="Order-infoType">{% trans "Статус оплаты" %}:
                                                        </div>
                                                        <div class="Order-infoContent">{{ last_order.get_payment_status_display }}
                                                        </div>
                                                    </div>
                                                    <div class="Order-info Order-info_status">
                                                        <div class="Order-infoType">{% trans "Статус доставки" %}:
                                                        </div>
                                                        <div class="Order-infoContent">{{ last_order.get_order_status_display }}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endif %}
                        </div>
                        <header class="Section-header">
                        <strong class="Section-title">{% trans "Последние просмотренные товары" %}
                        </strong>
                            <div class="Account-editLink"><a href="{% url "app_users:views_history" user.username %}">{% trans "История просмотра" %}</a>
                            </div>
                        </header>
                        <div class="Account-group">
                            <div class="Cards">
                                {% for item in watched_products %}
                                <div class="Card"><a class="Card-picture" href="{% url 'pages:product-detail' item.product.pk %}"><img src="/{% firstof item.product.icon.file 'static/assets/img/content/home/no-pic.png' %}" alt="card.jpg" /></a>
                                    <div class="Card-content">
                                        <strong class="Card-title"><a href="{% url 'pages:product-detail' item.product.pk %}">{{ item.product.title }}</a>
                                        </strong>
                                        <div class="Card-description">
                                            <div class="Card-cost"><span class="Card-price">от {{ item.min_price }} руб.</span>
                                            </div>
                                            <div class="Card-category">{{ item.product.category.title }}
                                            </div>
                                            <div class="Card-hover">
                                                <a class="Card-btn" href="{% url 'app_basket:add_to_cart'%}?offer_id={{ item.product.offers.first.pk }}">
                                                    <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg" />
                                                </a>
                                                <a class="Card-btn" href="{% url 'pages:add_to_comparison_list'%}?product={{ item.product.pk }}">
                                                    <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg" />
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                {% empty %}
                                <img src="{% static 'assets/img/content/home/no_res.png' %}" alt="no_results" width="450"/>
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

marketplace/templates/users/historyorder.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans "Навигация" %}
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:account" view.request.user.username %}">{% trans "Личный кабинет" %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:profile_edit" view.request.user.username %}">{% trans "Профиль" %}</a>
                                    </li>
                                    <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url "app_users:orders_history" %}">{% trans "История заказов" %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:views_history" view.request.user.username %}">{% trans "История просмотра" %}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Orders">
                        {% for order in orders %}
                        <div class="Order Order_anons">
                            <div class="Order-personal">
                                <div class="row">
                                    <div class="row-block"><a class="Order-title" href="{% url "app_users:order_detail" order.pk %}">{% trans "Заказ" %}&#32;<span class="Order-numberOrder">№{{ order.pk }}</span>&#32;{% trans "от" %}&#32;<span class="Order-dateOrder">{{ order.order_date|date:"d.m.Y" }}</span></a>
                                    </div>
                                    <div class="row-block">
                                        <div class="Order-info Order-info_delivery">
                                            <div class="Order-infoType">{% trans "Тип доставки" %}:
                                            </div>
                                            <div class="Order-infoContent">{{ order.delivery_type }}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_pay">
                                            <div class="Order-infoType">{% trans "Тип Оплата" %}:
                                            </div>
                                            <div class="Order-infoContent">{{ order.payment }}
                                            </div>
                                        </div>
                                        <div class="Order-info">
                                            <div class="Order-infoType">{% trans "Тип Общая стоимость" %}:
                                            </div>
                                            <div class="Order-infoContent"><span class="Order-price">{{ order.price }} $</span>
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">{% trans "Статус оплаты" %}:
                                            </div>
                                            <div class="Order-infoContent">{{ order.get_payment_status_display }}
                                            </div>
                                        </div>
                                        <div class="Order-info Order-info_status">
                                            <div class="Order-infoType">{% trans "Статус доставки" %}:
                                            </div>
                                            <div class="Order-infoContent">{{ order.get_order_status_display }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

marketplace/templates/users/historyview.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnLeft">
            <div class="wrap">
                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans "Навигация" %}
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:account" user.username %}">{% trans "Личный кабинет" %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:profile_edit" user.username %}">{% trans "Профиль" %}</a>
                                    </li>
                                    <li class="menu-item"><a class="menu-link" href="{% url "app_users:orders_history" %}">{% trans "История заказов" %}</a>
                                    </li>
                                    <li class="menu-item_ACTIVE menu-item"><a class="menu-link" href="{% url "app_users:views_history" user.username %}">{% trans "История просмотра" %} </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Section-content">
                    <div class="Account-group">
                        <div class="Cards">
                            {% for item in watched_products %}
                            <div class="Card"><a class="Card-picture" href="{% url 'pages:product-detail' item.product.pk %}"><img src="/{% firstof item.product.icon.file 'static/assets/img/content/home/no-pic.png' %}" alt="card.jpg" /></a>
                                <div class="Card-content">
                                    <strong class="Card-title"><a href="{% url 'pages:product-detail' item.product.pk %}">{{ item.product.title }}</a>
                                    </strong>
                                    <div class="Card-description">
                                        <div class="Card-cost"><span class="Card-price">от {{ item.min_price }} $</span>
                                        </div>
                                        <div class="Card-category">{{ item.product.category.title }}
                                        </div>
                                        <div class="Card-hover">
                                            <a class="Card-btn" href="{% url 'app_basket:add_to_cart'%}?offer_id={{ item.product.offers.first.pk }}">
                                                <img src="{% static 'assets/img/icons/card/cart.svg' %}" alt="cart.svg" />
                                            </a>
                                            <a class="Card-btn" href="{% url 'pages:add_to_comparison_list'%}?product={{ item.product.pk }}">
                                                <img src="{% static 'assets/img/icons/card/change.svg' %}" alt="change.svg" />
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% empty %}
                            <img src="{% static 'assets/img/content/home/no_res.png' %}" alt="no_results" width="450"/>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

marketplace/templates/users/login.html
{% extends 'base_mini.html' %}
{% load i18n %}

{% block main %}
<div class="wrapper">
    <div class="header">
        <h3 class="sign-in">{% trans "Вход" %}</h3>
    </div>
    <div class="clear"></div>
    <form method="post">
        {% csrf_token %}
        <div>
            {{ form.as_p }}
        </div>

        <div>
            <input type="submit" value="Войти" />
        </div>
        <a class="forgot-label" href="{% url 'app_users:password_reset' %}">{% trans "Забыли пароль" %}?</a>
        <a class="registr" href="{% url 'app_users:register' %}">
            {% trans "Регистрация" %}
        </a>
    </form>
</div>
{% endblock %}

marketplace/templates/users/logout.html
{% extends 'base_mini.html' %}
{% load i18n %}

{% block main %}
<div class="header">
    <h3 class="sign-in">{% trans "Выход из системы" %}</h3>
</div>
<p>{% trans "Вы успешно вышли из системы" %}.</p>
<p><a href="{% url 'app_users:login' %}">{% trans "Войти" %}</a> {% trans "снова" %}.</p>
{% endblock %}

marketplace/templates/users/password_reset_complete.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
<div class="wrapper">
    <div class="header">
        <h3 class="sign-in">{% trans "Сброс пароля" %}</h3>
    </div>
    <p>{% trans "Ваш пароль был успешно изменен" %}.</p>
</div>
{% endblock %}