marketplace/app_merch/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from .views import (AllDiscountView, CatalogView, DiscountDetailView,
                    DiscountListView, IndexView, OrderDeliveryView,
                    OrderPaymentView, OrderPurchaseView, OrderUserDataView,
                    ProductDetailView, PaymentView, ComparisonView,
                    import_products, add_to_comparison_list, remove_from_comparison_list, clear_comparison_list)

app_name = "pages"

urlpatterns = [
    path('', IndexView.as_view(), name='index-page'),
    path('products/', CatalogView.as_view(), name='catalog-view'),
    path('products/all_product_discounts/', AllDiscountView.as_view(), name='all-discounts'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('order/userdata/', OrderUserDataView.as_view(), name='order-step-1'),
    path('order/delivery/', OrderDeliveryView.as_view(), name='order-step-2'),
    path('order/payment/', OrderPaymentView.as_view(), name='order-step-3'),
    path('order/purchase/', OrderPurchaseView.as_view(), name='order-step-4'),
    path('order/send-payment/', PaymentView.as_view(), name='payment-view'),
    path("discounts/", DiscountListView.as_view(), name="discount_list"),
    path("discounts/<int:pk>/", DiscountDetailView.as_view(), name="discount_detail"),
    path("comparison/", ComparisonView.as_view(), name="comparison"),
    path("import-products/", import_products, name='import_page'),
    path("add_to_comparison_list/", add_to_comparison_list, name='add_to_comparison_list'),
    path("remove_from_comparison_list/", remove_from_comparison_list, name='remove_from_comparison_list'),
    path("clear_comparison_list/", clear_comparison_list, name='clear_comparison_list'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/app_users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (AccountView, CustomLoginView, CustomLogoutView, CustomPasswordResetConfirmView,
                    CustomPasswordResetDoneView, CustomPasswordResetView,
                    CustomRegisterView, OrderDetailView, OrdersHistoryView,
                    ProfileEditView, SellerView, ViewsHistoryView, CustomPasswordResetCompleteView)

app_name = "app_users"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
    path("password_reset/", CustomPasswordResetView.as_view(), name="password_reset"),
    path("password_reset/done/", CustomPasswordResetDoneView.as_view(), name="password_reset_done"),
    path("reset/<uidb64>/<token>/", CustomPasswordResetConfirmView.as_view(), name="password_reset_confirm"),
    path("password_reset/complete/", CustomPasswordResetCompleteView.as_view(), name="password_reset_complete"),
    path("register/", CustomRegisterView.as_view(), name="register"),
    path("seller/<int:pk>/", SellerView.as_view(), name="seller_detail"),
    path("profile/<slug:username>/", AccountView.as_view(), name="account"),
    path(
        "profile/<slug:username>/edit/", ProfileEditView.as_view(), name="profile_edit"
    ),
    path("my/orders/", OrdersHistoryView.as_view(), name="orders_history"),
    path("my/orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
    path(
        "profile/<slug:username>/views/",
        ViewsHistoryView.as_view(),
        name="views_history",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/marketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/clearcache/", include("clearcache.urls")),
    path("admin/", admin.site.urls),
    path("", include("app_merch.urls")),
    path("users/", include("app_users.urls")),
    path("cart/", include("app_basket.urls")),
    path('i18n/', include('django.conf.urls.i18n')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

marketplace/templates/orders/order_base.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Section Section_column Section_columnRight Section_columnWide Order">
            <div class="wrap">

                <div class="Section-column">
                    <div class="Section-columnSection">
                        <header class="Section-header">
                            <strong class="Section-title">{% trans "Прогресс заполнения" %}
                            </strong>
                        </header>
                        <div class="Section-columnContent">
                            <div class="NavigateProfile">
                                <ul class="menu menu_vt">
                                    <li {% if request.session.step == 1 %}class="menu-item_ACTIVE menu-item" {% else %}class="menu-item" {% endif %}><a class="menu-link" href="{% url 'pages:order-step-1' %}">{% trans "Шаг 1. Параметры пользователя" %}</a>
                                    </li>
                                    <li {% if request.session.step == 2 %}class="menu-item_ACTIVE menu-item" {% else %}class="menu-item" {% endif %}><a class="menu-link" href="{% url 'pages:order-step-2' %}">{% trans "Шаг 2. Способ доставки" %}</a>
                                    </li>
                                    <li {% if request.session.step == 3 %}class="menu-item_ACTIVE menu-item" {% else %}class="menu-item" {% endif %}><a class="menu-link" href="{% url 'pages:order-step-3' %}">{% trans "Шаг 3. Способ оплаты" %}</a>
                                    </li>
                                    <li {% if request.session.step == 4 %}class="menu-item_ACTIVE menu-item" {% else %}class="menu-item" {% endif %}><a class="menu-link" href="{% url 'pages:order-step-4' %}">{% trans "Шаг 4. Подтверждение заказа" %}</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="Section-content">
                    {% block order_step %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

marketplace/templates/orders/order_delivery.html
{% extends 'orders/order_base.html' %}
{% load i18n %}
{% load static %}

{% block order_step %}
    <form method="post" class="form">
    {% csrf_token %}
    {% if request.session.user_data %}
    <div class="Order-block Order-block_OPEN" id="step2">
        <header class="Section-header Section-header_sm">
            <h2 class="Section-title">{% trans "Шаг 2. Способ доставки" %}
            </h2>
        </header>
        <div class="form-group">
            {% if not request.session.user_data.delivery_data %}
            <div>
                <label class="toggle">
                    <input type="radio" name="delivery" value="{{ delivery_type.0.type }}" checked="checked" /><span class="toggle-box"></span><span
                        class="toggle-text">{{ delivery_type.0.type }}</span>
                </label>
            </div>
            {% for delivery in delivery_type|slice:"1:" %}
            <div>
                <label class="toggle">
                    <input type="radio" name="delivery" value="{{ delivery.type }}" {% if request.session.user_data.delivery_data.delivery.0 == delivery.type %} checked="checked" {% endif %}/><span class="toggle-box"></span><span
                        class="toggle-text">{{ delivery.type }}</span>
                </label>
            </div>
            {% endfor %}
            {% else %}
            {% for delivery in delivery_type %}
            <div>
                <label class="toggle">
                    <input type="radio" name="delivery" value="{{ delivery.type }}" {% if request.session.user_data.delivery_data.delivery.0 == delivery.type %} checked="checked" {% endif %}/><span class="toggle-box"></span><span
                        class="toggle-text">{{ delivery.type }}</span>
                </label>
            </div>
            {% endfor %}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.as_p }}
        <div class="Order-footer"><button type="submit" class="btn btn_success">{% trans "Дальше" %}</button>
        </div>
    </div>
    {% else %}
        <div align="center">
            <h2 class="Section-title">{% trans "Заполните информацию на" %} <a href="{% url 'pages:order-step-1' %}">{% trans "шаге 1" %}</a>, {% trans "пожалуйста" %}!</h2>
            <img src="{% static 'assets/img/content/home/bad_order.jpg' %}" alt="bad_order" style="max-width: 700px; width: 100%"/>
        </div>
    {% endif %}
    </form>
{% endblock %}

marketplace/templates/orders/order_payment.html
{% extends 'orders/order_base.html' %}
{% load i18n %}
{% load static %}

{% block order_step %}
    <form method="post" class="form">
    {% csrf_token %}
    {% if request.session.user_data.delivery_data %}
        <div class="Order-block Order-block_OPEN" id="step3">
            <header class="Section-header Section-header_sm">
                <h2 class="Section-title">{% trans "Шаг 3. Способ оплаты" %}
                </h2>
            </header>
            <div class="form-group">
                {% if not request.session.user_data.payment_data %}
                <div>
                    <label class="toggle">
                        <input type="radio" name="pay" value="{{ payment_type.0.title }}" checked="checked" /><span class="toggle-box"></span><span
                            class="toggle-text">{{ payment_type.0.title }}</span>
                    </label>
                </div>
                {% for payment in payment_type|slice:"1:" %}
                <div>
                    <label class="toggle">
                        <input type="radio" name="pay" value="{{ payment.title }}" {% if request.session.user_data.payment_data.pay.0 == payment.title %} checked="checked" {% endif %}/><span
                            class="toggle-box"></span><span class="toggle-text">{{ payment.title }}</span>
                    </label>
                </div>
                {% endfor %}
                {% else %}
                {% for payment in payment_type %}
                <div>
                    <label class="toggle">
                        <input type="radio" name="pay" value="{{ payment.title }}" {% if request.session.user_data.payment_data.pay.0 == payment.title %} checked="checked" {% endif %}/><span
                            class="toggle-box"></span><span class="toggle-text">{{ payment.title }}</span>
                    </label>
                </div>
                {% endfor %}
                {% endif %}
                <div style="margin-bottom: 150px"></div>
            </div>
            <div class="Order-footer"><button class="btn btn_success" type="submit">{% trans "Дальше" %}</button>
            </div>
        </div>
    {% else %}
        <div align="center">
            <h2 class="Section-title">{% trans "Заполните информацию на" %} <a href="{% url 'pages:order-step-2' %}">{% trans "шаге 2" %}</a>, {% trans "пожалуйста" %}!</h2>
            <img src="{% static 'assets/img/content/home/bad_order.jpg' %}" alt="bad_order" style="max-width: 700px; width: 100%"/>
        </div>
    {% endif %}
    </form>
{% endblock %}

marketplace/templates/orders/order_purchase.html
{% extends 'orders/order_base.html' %}
{% load i18n %}
{% load static %}
{% load product_discount_tags %}

{% block order_step %}
    <form method="post" class="form">
    {% csrf_token %}
    {% if request.session.user_data.payment_data %}
        <div class="Order-block Order-block_OPEN" id="step4">
            <header class="Section-header Section-header_sm">
                <h2 class="Section-title">{% trans "Шаг 4. Подтверждение заказа" %}
                </h2>
            </header>
            <!--+div.Order.-confirmation-->
            <div class="Order-infoBlock">
                <div class="Order-personal">
                    <div class="row">
                        <div class="row-block">
                            <div class="Order-info">
                                <div class="Order-infoType">{% trans "ФИО" %}:
                                </div>
                                <div class="Order-infoContent">{{ request.session.user_data.name.0 }}
                                </div>
                            </div>
                            <div class="Order-info">
                                <div class="Order-infoType">{% trans "Телефон" %}:
                                </div>
                                <div class="Order-infoContent">{{ request.session.user_data.phone.0 }}
                                </div>
                            </div>
                            <div class="Order-info">
                                <div class="Order-infoType">Email:
                                </div>
                                <div class="Order-infoContent">{{ request.session.user_data.mail.0 }}
                                </div>
                            </div>
                        </div>
                        <div class="row-block">
                            <div class="Order-info Order-info_delivery">
                                <div class="Order-infoType">{% trans "Тип доставки" %}:
                                </div>
                                <div class="Order-infoContent">{{ request.session.user_data.delivery_data.delivery.0 }}
                                </div>
                            </div>
                            <div class="Order-info">
                                <div class="Order-infoType">{% trans "Город" %}:
                                </div>
                                <div class="Order-infoContent">{{ request.session.user_data.delivery_data.city.0 }}
                                </div>
                            </div>
                            <div class="Order-info">
                                <div class="Order-infoType">{% trans "Адрес" %}:
                                </div>
                                <div class="Order-infoContent">{{ request.session.user_data.delivery_data.address.0 }}
                                </div>
                            </div>
                            <div class="Order-info Order-info_pay">
                                <div class="Order-infoType">{% trans "Оплата" %}:
                                </div>
                                <div class="Order-infoContent">{{ request.session.user_data.payment_data.pay.0 }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="Cart Cart_order">
                    {% for item in cart_items %}
                    <div class="Cart-product">
                        <div class="Cart-block Cart-block_row">
                            <div class="Cart-block Cart-block_pict"><a class="Cart-pict" href="#"><img class="Cart-img"
                                                                                                       src="/{% firstof item.product.icon.file 'static/assets/img/content/home/no-pic.png' %}"
                                                                                                       alt="card.jpg"/></a>
                            </div>
                            <div class="Cart-block Cart-block_info"><a class="Cart-title" href="{% url 'pages:product-detail' item.product.pk %}">{{ item.product.title }}</a>
                                <div class="Cart-desc">{{ item.product.description }}
                                </div>
                            </div>
                            {% if item.product.discounts %}
                            <div class="Cart-block Cart-block_price">
                                <div class="Cart-price"><del style="color: #df3349">{{ item.price }}</del>
                                </div>
                                <div class="Cart-price">{% avg_discount_price item.product %}
                                </div>
                            </div>
                            {% else %}
                            <div class="Cart-block Cart-block_price">
                                <div class="Cart-price">{{ item.price }}
                                </div>
                            </div>
                            {% endif %}
                        </div>
                        <div class="Cart-block Cart-block_row">
                            <div class="Cart-block Cart-block_amount">{{ item.amount }}
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="Cart-total">
                        <div class="Cart-block Cart-block_total">
                            <strong class="Cart-title">{% trans "Итого" %}:
                            </strong><span class="Cart-price">{{ total_price }}</span>
                        </div>
                        <div class="Cart-block">
                            <button class="btn btn_primary btn_lg" type="submit">{% trans "Оплатить" %}
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% else %}
        <div align="center">
            <h2 class="Section-title">{% trans "Заполните информацию на" %} <a href="{% url 'pages:order-step-3' %}">{% trans "шаге 3" %}</a>, {% trans "пожалуйста" %}!</h2>
            <img src="{% static 'assets/img/content/home/bad_order.jpg' %}" alt="bad_order" style="max-width: 700px; width: 100%"/>
        </div>
    {% endif %}
    </form>
{% endblock %}

marketplace/templates/orders/order_user_data.html
{% extends "orders/order_base.html" %}
{% load i18n %}
{% load static %}

{% block order_step %}
    {% if cart_items %}
    <form method="post" class="form">
    {% csrf_token %}
    <div class="Order-block Order-block_OPEN" id="step1">
        <header class="Section-header Section-header_sm">
            <h2 class="Section-title">{% trans "Шаг 1. Параметры пользователя" %}
            </h2>
        </header>
        <div class="row">
            <div class="row-block">
                {{ form.as_p }}
            </div>
            {% if not user.is_authenticated %}
                <div class="row-block">
                    <div class="form-group">
                        <label class="form-label" for="password">{% trans "Пароль" %}
                        </label>
                        <input class="form-input" id="password" name="password" type="password" data-validate="require"
                               placeholder="Введите ваш пароль"/>
                    </div>
                    <div class="form-group">
                        <label class="form-label" for="passwordReply">{% trans "Подтверждение пароля" %}
                        </label>
                        <input class="form-input" id="passwordReply" name="passwordReply" type="password"
                               data-validate="require" placeholder="Введите пароль повторно"/>
                    </div>
                    <div class="form-group"><a class="btn btn_muted Order-btnReg" href="{% url 'app_users:login' %}">{% trans "Я уже зарегистрирован" %}</a>
                    </div>
                </div>
            {% endif %}
        </div>
        {% if request.user.is_authenticated %}
            <div class="Order-footer"><button class="btn btn_success" type="submit">{% trans "Дальше" %}</button>
            </div>
        {% else %}
            <div class="Order-footer"><button class="btn btn_success" type="submit">{% trans "Зарегистрироваться" %}</button>
            </div>
        {% endif %}
    </div>
    </form>
    {% else %}
        <h2 class="Section-title">{% trans "Ваша корзина пуста" %}. <a href="{% url 'pages:catalog-view' %}">{% trans "Продолжить покупки" %}.</a></h2>
        <div align="center">
            <img src="{% static 'assets/img/content/home/empty_order.svg'%}" alt="empty_order" style="max-width: 350px"/>
        </div>
    {% endif %}

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery.inputmask.min.js' %}"></script>

    <script>
        document.getElementById('id_phone').addEventListener('input', function (e) {
            var x = e.target.value.replace(/\D/g, '').match(/(\d{0,3})(\d{0,3})(\d{0,4})/);
            e.target.value = '(' +x[1] + ') '+ x[2] + '-' + x[3]

            if (e.target.value.length < 5) {
                e.target.value = ''
            }
        });

        window.addEventListener("load", (event) => {
            let e = document.getElementById('id_phone')
            var x = e.value.slice(1).replace(/\D/g, '').match(/(\d{0,3})(\d{0,3})(\d{0,4})/);
            e.value = '(' +x[1] + ') '+ x[2] + '-' + x[3]

            if (e.value.length < 5) {
                e.value = ''
            }
        });
    </script>

{% endblock %}

marketplace/templates/orders/payment.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% trans "Оплата" %}
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="{% url 'pages:index-page' %}">{% trans "Главная" %}</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans "Оплата" %}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <form class="form Payment" action="#" method="post">
                    {% csrf_token %}
                    <div class="Payment-card">
                        <div class="form-group">
                            {{ form.as_p }}
                        </div>
                        <div class="form-group"><a class="btn btn_success Payment-generate" href="#">{% trans "Сгенирировать случайный счет" %}</a>
                        </div>
                    </div>
                    <div class="Payment-pay"><button class="btn btn_primary" href="#">{% trans "Оплатить" %}</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

marketplace/templates/orders/payment_progress.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}

{% block content %}
    <div class="Middle Middle_top">
        <div class="Middle-top">
            <div class="wrap">
                <div class="Middle-header">
                    <h1 class="Middle-title">{% trans "Ожидание оплаты" %}
                    </h1>
                    <ul class="breadcrumbs Middle-breadcrumbs">
                        <li class="breadcrumbs-item"><a href="{% url 'pages:index-page' %}">{% trans "Главная" %}</a>
                        </li>
                        <li class="breadcrumbs-item breadcrumbs-item_current"><span>{% trans "Ожидание оплаты" %}</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="Section">
            <div class="wrap">
                <div class="ProgressPayment">
                    <div class="ProgressPayment-title">{% trans "Ждем подтверждения оплаты платежной системой" %}
                    </div>
                    <div class="ProgressPayment-icon">
                        <div class="cssload-thecube">
                            <div class="cssload-cube cssload-c1"></div>
                            <div class="cssload-cube cssload-c2"></div>
                            <div class="cssload-cube cssload-c4"></div>
                            <div class="cssload-cube cssload-c3"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        setTimeout(function() {
            window.location.href = "{% url 'app_users:order_detail' request.session.order_id %}";
        }, 5000);
    </script>

{% endblock %}